
import dotenv from 'dotenv';
dotenv.config();

import { createClient } from '@supabase/supabase-js';

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseKey) {
    console.error('Missing credentials');
    process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey);

async function test() {
    console.log('Testing Products query...');

    // Imitating the query structure from product-repository
    // Note: repository seems to default to using drizzle alias which might internally map
    // But if using raw query or sql, it must match DB.
    // The repository uses Drizzle ORM which handles mapping IF the schema definitions are correct vs the DB.

    // However, I see "discountPrice" (camel) in schema.ts definition: discountPrice: decimal('discountPrice')
    // But in Postgres it is likely snake_case 'discount_price' if generated by standard conventions or init.sql.
    // Let's check init schema sql again.
    // 0000_init_schema.sql: discount_price DECIMAL

    // So schema.ts SAYS "discountPrice" map to "discountPrice" string in column name?
    // export const products = pgTable('products', {
    //   discountPrice: decimal('discountPrice'), -> This means column name IS "discountPrice" in quotes.
    // but init_schema.sql says: discount_price.

    // Wait, if 0000_init_schema.sql created the DB, then columns are snake_case.
    // But schema.ts uses camelCase strings in column definition? 
    //   discountPrice: decimal('discountPrice')
    // This is the mismatch! It should be decimal('discount_price').

    // Let's verify by trying to select 'discountPrice' vs 'discount_price' via supabase.

    const { error: errorCamel } = await supabase.from('products').select('discountPrice').limit(1);
    console.log('Select discountPrice error:', errorCamel?.message || 'None');

    const { error: errorSnake } = await supabase.from('products').select('discount_price').limit(1);
    console.log('Select discount_price error:', errorSnake?.message || 'None');

    const { error: errorLowerCamel } = await supabase.from('products').select('discountPrice').limit(1);
    console.log('Select discountPrice error:', errorLowerCamel?.message || 'None');
}

test();
